apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: microservice-archetype
  description: microservice-archetype main website
spec:
  type: website
  lifecycle: production
  owner: team-a
  system: microservice-archetype-portal
