kind: Service
apiVersion: v1
metadata: 
  name: springcloud-demoservice
  labels:
    app: springcloud-demoservice
spec: 
  ports:    
     - protocol: TCP
       port: 8085
       targetPort: 8080
  selector: 
      app: springcloud-demo   
  type: NodePort