apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: AddressService
  description: Address main website
  annotations:
    jenkins.io/github-folder: 'address-rest-api'
    backstage.io/techdocs-ref: url:https://github.com/prakashg1984/TechPocWorkspace/tree/master/address-rest-api
    sonarqube.org/project-key: address-rest-api
    backstage.io/kubernetes-id: address-rest-api
    kafka.apache.org/consumer-groups: cluster-name/consumer-group-name
  tags:
    - java
    - springboot
    - address
  links:
    - url: https://github.com/prakashg1984/TechPocWorkspace/tree/master/address-rest-api
      title: Github URL
      icon: web
spec:
  type: service
  lifecycle: production
  owner: OCE-ATT
  system: OCE Portal
  providesApis:
    - address-rest-api
