apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-ui
spec:
  selector:
    matchLabels:
      app: springboot-ui
  template:
    metadata:
      labels:
        app: springboot-ui
    spec:
      containers:
      - name: springboot-ui
        image: ${docker.registry}:springboot-ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
