apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  # file-like keys
  application.properties: |
    my.message=configmapmessage
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
