kind: Service
apiVersion: v1
metadata: 
  name: testnewmsprojectkubeservice
  labels:
    app: testnewmsprojectkubeservice
spec: 
  ports:    
     - protocol: TCP
       port: 8085
       targetPort: 8080
  selector: 
      app: testnewmsprojectkube   
  type: NodePort